from ipo_financial_agent.agents.report_writer import ReportWriterAgent


class MustNotBeCalledClient:
    def complete_text(self, **_: object) -> str:
        raise AssertionError("large financial report must not be regenerated by LLM")


def test_large_statement_report_uses_grounded_deterministic_draft() -> None:
    draft = (
        "# 公司尽调报告\n\n### 三大财务报表（招股书原表还原）\n\n"
        "#### 资产负债表\n| 项目 | 2024年 |\n|---|---|\n| 现金 | 100 |"
    )
    result = ReportWriterAgent(MustNotBeCalledClient()).write_diligence_draft(
        company="示例公司",
        grounded_draft=draft,
        agent_messages=[],
    )
    assert result == draft
